#!/bin/sh
#
# @name UAV NUC measured quadrotor SITL
#
# @type Quadrotor x
#
# @maintainer UAV NUC project
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.11744
param set-default CA_ROTOR0_PY 0.11744
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.11744
param set-default CA_ROTOR1_PY -0.11744
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.11744
param set-default CA_ROTOR2_PY -0.11744
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.11744
param set-default CA_ROTOR3_PY 0.11744
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
